version: "2"
services:
  zoo1:
    container_name: cm_zookeeper1
    image: zookeeper:3.4.10
    ports:
     - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
     - ./out/zookeeper1/data:/data
     - ./out/zookeeper1/datalog:/datalog
  kafka:
    container_name: cm_kafka
    image: ches/kafka:0.10.2.1
    restart: always
    ports:
     - "9092:9092"
     - "1099:1099"
    environment:
      # Hostname and port which kafka will tell to consumers
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_BROKER_ID: "1"
      KAFKA_PORT: "9092"
      ZOOKEEPER_CONNECTION_STRING: "zoo1:2181"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    volumes:
      - ./out/kafka1:/data
    depends_on:
      - zoo1
  kafka_manager:
    container_name: cm_kafka_manager
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    environment:
      ZK_HOSTS: "zoo1:2181"
      # https://github.com/yahoo/kafka-manager/blob/master/conf/application.conf#L13
      APPLICATION_SECRET: "dilbert"