---

version: '3.3'
services:

  cm-bitfinex-connector:
    image: connectors/bitfinex:latest
    environment:
       KAFKA_CONNECTION: cyber_markets_fast_data_dev:9092

  cm-hitbtc-connector:
      image: connectors/hitbtc:latest
      environment:
         KAFKA_CONNECTION: cyber_markets_fast_data_dev:9092
