version: 2


defaults:

  container: &default_container
    working_directory: ~/build
    docker:
      - image: circleci/openjdk:8-jdk

  release_filter: &release_filter
    filters:
      tags:
        only: /^release-.*/
      branches:
        ignore: /.*/


jobs:

  build_connectors:
    <<: *default_container
    steps:
      - checkout
      - restore_cache:
          keys:
            - connectors-core-dependencies-{{ checksum "build.gradle" }}
            - connectors-core-dependencies
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
      - run:
          name: Test and build connectors project
          command: |
            ./gradlew -p ./connectors-bitfinex clean build
            ./gradlew -p ./connectors-bitstamp clean build
            ./gradlew -p ./connectors-hitbtc clean build
            ./gradlew -p ./connectors-poloniex clean build
      - save_cache:
          key: connectors-core-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/

  build_stream-api:
    <<: *default_container
    steps:
      - checkout
      - restore_cache:
          keys:
            - api-dependencies-{{ checksum "build.gradle" }}
            - api-dependencies
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
      - run:
          name: Test and build stream-api project
          command: ./gradlew -p ./stream-api clean build
      - save_cache:
          key: api-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/

  deploy_connectors-bitfinex_image:
     <<: *default_container
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.05.0-ce
       - run:
           name: Build connectors-bitfinex docker image
           command: |
             docker build -t build/cm-connectors-bitfinex -f ./devops/connectors/bitfinex/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/cm-connectors-bitfinex cybernode/cm-connectors-bitfinex:$CIRCLE_TAG
             docker push cybernode/cm-connectors-bitfinex:$CIRCLE_TAG
             docker tag build/cm-connectors-bitfinex cybernode/cm-connectors-bitfinex:latest
             docker push cybernode/cm-connectors-bitfinex:latest

  deploy_connectors-bitstamp_image:
       <<: *default_container
       steps:
         - checkout
         - setup_remote_docker:
             version: 17.05.0-ce
         - run:
             name: Build connectors-bitstamp docker image
             command: |
               docker build -t build/cm-connectors-bitstamp -f ./devops/connectors/bitstamp/Dockerfile ./
               docker login -u $DOCKER_USER -p $DOCKER_PASS
               docker tag build/cm-connectors-bitstamp cybernode/cm-connectors-bitstamp:$CIRCLE_TAG
               docker push cybernode/cm-connectors-bitstamp:$CIRCLE_TAG
               docker tag build/cm-connectors-bitstamp cybernode/cm-connectors-bitstamp:latest
               docker push cybernode/cm-connectors-bitstamp:latest

  deploy_connectors-hitbtc_image:
         <<: *default_container
         steps:
           - checkout
           - setup_remote_docker:
               version: 17.05.0-ce
           - run:
               name: Build connectors-hitbtc docker image
               command: |
                 docker build -t build/cm-connectors-hitbtc -f ./devops/connectors/hitbtc/Dockerfile ./
                 docker login -u $DOCKER_USER -p $DOCKER_PASS
                 docker tag build/cm-connectors-hitbtc cybernode/cm-connectors-hitbtc:$CIRCLE_TAG
                 docker push cybernode/cm-connectors-hitbtc:$CIRCLE_TAG
                 docker tag build/cm-connectors-hitbtc cybernode/cm-connectors-hitbtc:latest
                 docker push cybernode/cm-connectors-hitbtc:latest

  deploy_connectors-poloniex_image:
         <<: *default_container
         steps:
           - checkout
           - setup_remote_docker:
               version: 17.05.0-ce
           - run:
               name: Build connectors-poloniex docker image
               command: |
                 docker build -t build/cm-connectors-poloniex -f ./devops/connectors/poloniex/Dockerfile ./
                 docker login -u $DOCKER_USER -p $DOCKER_PASS
                 docker tag build/cm-connectors-poloniex cybernode/cm-connectors-poloniex:$CIRCLE_TAG
                 docker push cybernode/cm-connectors-poloniex:$CIRCLE_TAG
                 docker tag build/cm-connectors-poloniex cybernode/cm-connectors-poloniex:latest
                 docker push cybernode/cm-connectors-poloniex:latest

  deploy_connectors-etherdelta_image:
           <<: *default_container
           steps:
             - checkout
             - setup_remote_docker:
                 version: 17.05.0-ce
             - run:
                 name: Build connectors-etherdelta docker image
                 command: |
                   docker build -t build/cm-connectors-etherdelta -f ./devops/connectors/etherdelta/Dockerfile ./
                   docker login -u $DOCKER_USER -p $DOCKER_PASS
                   docker tag build/cm-connectors-etherdelta cybernode/cm-connectors-etherdelta:$CIRCLE_TAG
                   docker push cybernode/cm-connectors-etherdelta:$CIRCLE_TAG
                   docker tag build/cm-connectors-etherdelta cybernode/cm-connectors-etherdelta:latest
                   docker push cybernode/cm-connectors-etherdelta:latest


  deploy_stream-api_image:
     <<: *default_container
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.05.0-ce
       - run:
           name: Build stream-api docker image
           command: |
             docker build -t build/cm-stream-api -f ./devops/stream-api/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/cm-stream-api cybernode/cm-stream-api:$CIRCLE_TAG
             docker push cybernode/cm-stream-api:$CIRCLE_TAG
             docker tag build/cm-stream-api cybernode/cm-stream-api:latest
             docker push cybernode/cm-stream-api:latest

  deploy_kafka-connectors_image:
       <<: *default_container
       steps:
         - checkout
         - setup_remote_docker:
             version: 17.05.0-ce
         - run:
             name: Build kafka-connectors docker image
             command: |
               docker build -t build/cm-kafka-connectors -f ./devops/kafka-connectors/Dockerfile ./
               docker login -u $DOCKER_USER -p $DOCKER_PASS
               docker tag build/cm-kafka-connectors cybernode/cm-kafka-connectors:$CIRCLE_TAG
               docker push cybernode/cm-kafka-connectors:$CIRCLE_TAG
               docker tag build/cm-kafka-connectors cybernode/cm-kafka-connectors:latest
               docker push cybernode/cm-kafka-connectors:latest

workflows:
  version: 2

  connectors_build:
    jobs:
      - build_connectors:
          filters:
            tags:
              only: /.*/
      - deploy_connectors-bitfinex_image:
          <<: *release_filter
          requires:
            - build_connectors
      - deploy_connectors-bitstamp_image:
          <<: *release_filter
          requires:
            - build_connectors
      - deploy_connectors-hitbtc_image:
          <<: *release_filter
          requires:
            - build_connectors
      - deploy_connectors-poloniex_image:
          <<: *release_filter
          requires:
            - build_connectors
      - deploy_connectors-etherdelta_image:
          <<: *release_filter
          requires:
            - build_connectors

  stream-api_build:
    jobs:
      - build_stream-api:
          filters:
            tags:
              only: /.*/
      - deploy_stream-api_image:
          <<: *release_filter
          requires:
            - build_stream-api

  kafka-connectors_build:
    jobs:
      - deploy_kafka-connectors_image:
          <<: *release_filter