---

version: '3.3'
services:


  fast-data-dev:
    container_name: cm-fast-data-dev
    image: landoop/fast-data-dev:latest
    ports:
      - "3030:3030"
      - "9092:9092"
      - "2181:2181"
      - "9581-9584:9581-9584"
      - "8081-8083:8081-8083"
    environment:
       RUNTESTS: 0
       SAMPLEDATA: 0
       FORWARDLOGS: 0
       ADV_HOST: cm-fast-data-dev

  cm-bitfinex:
    container_name: cm-bitfinex
    image: cybernode/cm-connectors-bitfinex:latest
    environment:
        KAFKA_CONNECTION: cm-fast-data-dev:9092

  cm-bitstamp:
      container_name: cm-bitstamp
      image: cybernode/cm-connectors-bitstamp:latest
      environment:
          KAFKA_CONNECTION: cm-fast-data-dev:9092

  cm-hitbtc:
      container_name: cm-hitbtc
      image: cybernode/cm-connectors-hitbtc:latest
      environment:
          KAFKA_CONNECTION: cm-fast-data-dev:9092

  cm-poloniex:
      container_name: cm-poloniex
      image: cybernode/cm-connectors-poloniex:latest
      environment:
          KAFKA_CONNECTION: cm-fast-data-dev:9092